contact_links:
- name: ğŸ¤” Have questions or need support?
  url: https://github.com/yasserbdj96/hexor/discussions
  about: This is a place for the community to exchange ideas and recipes
- name: ğŸ’¬ gitter (chat)
  url: https://gitter.im/yasserbdj96/hexor
  about: Chat with devs
